FROM rasa/rasa-sdk:3.6.2

USER root

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/actions

USER 1001
EXPOSE 5005
CMD ["start", "--actions", "actions"]
